### ISSUE TITLE
MyThrustReconstruction processor

### ISSUE THREAD

**Issue by elijahcm** [iLCSoft/MarlinReco#20]
Hi,

I tried running the MyThrustReconstruction processor (see line 468) but I get the error "unknown processor with type ThrustReconstruction". Can you direct me towards a working example?

Thanks.

**Comment by andresailer** [comment]
It seems this processor and others in Analysis/EventShapes are not compiled at the moment, unless MARLINRECO_Fortran is set s a build option.

PS: Not that it really matters unless there are other things wrong, but line 468 of what?

**Comment by gaede** [comment]
Should be fixed with #22.

**Comment by elijahcm** [comment]
@andresailer, sorry, line 468 of MarlinReco/examples/LDC/steer_ldc.xml. Was just pointing to where the "MyThrustReconstruction" processor is located in the example steering file.
