### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by andb0t** [iLCSoft/MarlinReco#32]
- OS version: e.g. SLC6
 - Compiler version: e.g GCC 6.2

When compiling the MarlinReco package, a massive amount of compiler warnings shows up. I quote the inofficial iLCSoft coding conventions in [Frank Gaede's talk](http://ilcsoft.desy.de/portal/e279/e281/infoboxContent282/sw_guidelines_ilcsoft.pdf) at the ILCSoft Meeting DESY, May 03, 2006, slide 13:

> modify code until __NO__ warnings persists

What do you think about this? If you don't agree, why is it reasonable to leave all those warnings unfixed? Also, would you like your contributors to fix their compiler warnings before submitting PRs?

**Comment by petricm** [comment]
You should only fix the warnings that  come from code that you add (e.g. you should not increase the number of warnings in the package). However if you modify a existing processor it would be appreciated if you could also fix some warnings from it.

**Comment by gaede** [comment]
We are (for quite some time) still in a transition period where we have enabled a lot more warnings and simply did not yet manage to address them all ....
However my recommendation:
`
modify code until NO warnings persists
`
is of course still true !
So please try to make sure that the processor you are working on has no warnings.
