### ISSUE TITLE
Isolated lepton tagging not safe against empty vertex collection

### ISSUE THREAD

**Issue by beyerja** [iLCSoft/MarlinReco#56]
I tried running the IsolatedLeptonTaggingProcessor on the mc-opt-3 (iLCSoft v02-00-02) 1TeV samples and got a segmentation fault at one of the files. I'm a pretty certain the reason is that somehow the primary vertex collection in the event is empty and the tagger has no check for that.
@tjunping Could you please implement a check that the vertex collection is not empty?
It would also be nice to have some streamlog_out(DEBUG) print-out statements in the processor, it took me some time to find where the error came from.

 - OS version: e.g. SLC6
 - Compiler version: e.g GCC 4.9
 - Package version: cvmfs version of iLCSoft v02-00-02
 - Reproduced by: Running e.g. the IsolatedLeptonTaggingProcessor on this event: 
```dumpevent /pnfs/desy.de/ilc/prod/ilc/mc-opt-3/ild/dst-merged/1000-B1b_ws/6f_xxxxZ/ILD_l5_o1_v02/v02-00-02/rv02-00-02.sv02-00-02.mILD_l5_o1_v02.E1000-B1b_ws.I35920.Pxxxxee.eR.pL.n001.d_dstm_11125_0.slcio 3526 | less```
 - Input: /pnfs/desy.de/ilc/prod/ilc/mc-opt-3/ild/dst-merged/1000-B1b_ws/6f_xxxxZ/ILD_l5_o1_v02/v02-00-02/rv02-00-02.sv02-00-02.mILD_l5_o1_v02.E1000-B1b_ws.I35920.Pxxxxee.eR.pL.n001.d_dstm_11125_0.slcio
[test.xml.txt](https://github.com/iLCSoft/MarlinReco/files/2472954/test.xml.txt) 
- Output: 
[isolep_log.txt](https://github.com/iLCSoft/MarlinReco/files/2472953/isolep_log.txt)
 - Goal: Having IsolatedLeptonTagging running without segfault even if something is wrong with the sample.

**Comment by rete** [comment]
The issue has been reported in the ILDAnaSoft/ILDDoc pages here: https://github.com/ILDAnaSoft/ILDDoc/issues/21.
The issue page contains also a workaround for analysis.
I believe I can close this issue.

**Comment by beyerja** [comment]
@rete I would disagree, I think this issue should stay open.
While there is a workaround for the problem with the primary vertexing, the issue here is concerning the IsolatedLeptonTaggingProcessor. 
Namely that it crashes with a segmentation fault when run on an event with an empty primary vertex collection.
This is not yet fixed.

**Comment by rete** [comment]
@beyerja I've opened a pull request. This should be enough. Can you confirm that this is enough to fix your issue ?

**Comment by beyerja** [comment]
@rete Looks good to me! Thanks!
