### ISSUE TITLE
unoptimal dEdx angular correction for all samples reconstructed with  v02-02 

### ISSUE THREAD

**Issue by airqui** [iLCSoft/MarlinReco#90]
Just to keep track of this issue.
Discussed in https://agenda.linearcollider.org/event/9197/

Besides the needed changes in PIDTools/ , we are also working in a optimization of the dEdxAnalyser in ILDPerformance

**Comment by tmadlener** [comment]
This has been fixed by #91, right? Otherwise, feel free to open this again.
